#!/usr/bin/env python3
"""Generate docs/inventory.md and THIRD-PARTY-NOTICES.md (NFR-12).

Sources: `cargo license --json` for Rust crates, node_modules package.json
files for the runtime npm dependencies, scripts/fetch-deps.ps1 for the
model and binary checksums, and assets/fonts for the bundled fonts.
Run from the repository root: python scripts/inventory.py
"""
import json
import os
import re
import subprocess
import sys
from collections import Counter, defaultdict

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(root)


def cargo_license():
    out = subprocess.run(["cargo", "license", "--json"], capture_output=True, text=True, encoding="utf-8", errors="replace", check=True).stdout
    return json.loads(out)


def npm_runtime():
    pkg = json.load(open("package.json", encoding="utf-8"))
    rows = []
    for name in sorted(pkg.get("dependencies", {})):
        try:
            j = json.load(open(os.path.join("node_modules", name, "package.json"), encoding="utf-8"))
            rows.append((name, j.get("version", "?"), j.get("license", "?"), j.get("repository", {}).get("url", "") if isinstance(j.get("repository"), dict) else ""))
        except OSError:
            rows.append((name, "?", "not installed", ""))
    return rows


def models():
    txt = open("scripts/fetch-deps.ps1", encoding="utf-8").read()
    rows = []
    for m in re.finditer(r'dir = "(\w+)"; url = "([^"]+)"; sha = "([0-9a-f]+)"', txt):
        rows.append((f"models/{m.group(1)}/eng.traineddata", m.group(2), m.group(3), "Apache-2.0 (tesseract-ocr/tessdata)"))
    for m in re.finditer(r'file = "([^"]+)"; url = "([^"]+)"; sha = "([0-9a-f]+)"', txt):
        rows.append((f"models/{m.group(1)}", m.group(2), m.group(3), "Apache-2.0 (ocrs-models)"))
    pd = re.search(r'\$pdfiumTag = "([^"]+)"', txt)
    ps = re.search(r'\$pdfiumSha = "([0-9a-f]+)"', txt)
    if pd and ps:
        rows.append(("third_party/pdfium/bin/pdfium.dll", f"bblanchon/pdfium-binaries {pd.group(1)}", ps.group(1), "BSD-3-Clause (PDFium) / Apache-2.0 (binaries)"))
    return rows


def fonts():
    rows = []
    d = "src/assets/fonts"
    if os.path.isdir(d):
        for f in sorted(os.listdir(d)):
            if f.lower().endswith((".ttf", ".otf")):
                rows.append((f, "SIL Open Font License 1.1"))
    return rows


def main():
    crates = cargo_license()
    by_license = defaultdict(list)
    for c in crates:
        by_license[c.get("license") or "UNKNOWN"].append(c)
    npm = npm_runtime()
    mods = models()
    fnt = fonts()

    inv = ["# Dependency, model, and asset inventory", "", "Generated by `python scripts/inventory.py` (NFR-12). Regenerate after changing dependencies.", ""]
    inv += ["## Rust crates", "", f"{len(crates)} crates in the dependency graph (all targets). Licenses:", ""]
    inv += ["| License | Crates |", "| --- | --- |"]
    for lic, cs in sorted(by_license.items(), key=lambda kv: -len(kv[1])):
        inv.append(f"| {lic} | {len(cs)} |")
    copyleft = [c for c in crates if "GPL" in (c.get("license") or "") and "OR" not in (c.get("license") or "")]
    inv += ["", f"Copyleft-only crates: {len(copyleft)}" + ("" if not copyleft else " — " + ", ".join(c['name'] for c in copyleft)), ""]
    inv += ["Direct workspace dependencies are listed in `docs/crates.md`; the full list with versions and licenses is in `THIRD-PARTY-NOTICES.md`.", ""]
    inv += ["## npm runtime dependencies", "", "| Package | Version | License |", "| --- | --- | --- |"]
    inv += [f"| {n} | {v} | {l} |" for n, v, l, _ in npm]
    inv += ["", "Build-time npm tooling (Vite, Svelte compiler, TypeScript, Vitest, Tauri CLI) does not ship in the installer.", ""]
    inv += ["## Native binaries and models", "", "| File | Source | SHA-256 | License |", "| --- | --- | --- | --- |"]
    inv += [f"| `{f}` | {src} | `{sha[:16]}…` | {lic} |" for f, src, sha, lic in mods]
    inv += ["", "Tesseract 5.5.2 and Leptonica are statically linked from vcpkg (`x64-windows-static-md`), both Apache-2.0 / BSD-2-Clause.", ""]
    inv += ["## Fonts", "", "| File | License |", "| --- | --- |"] + [f"| `{f}` | {l} |" for f, l in fnt] + [""]
    inv += ["## Lexicons", "", "See `fixtures/README.md`: Hunspell en_GB-large (SCOWL, MIT-like), Webster 1913 headwords (public domain).", ""]
    open("docs/inventory.md", "w", encoding="utf-8", newline="\n").write("\n".join(inv))

    notices = ["# Third-party notices", "", "SBWB is MIT licensed. It links or bundles the following third-party software. Full license texts are available from each project; the crate texts are in the Cargo registry sources (`cargo license` lists them).", ""]
    notices += ["## Rust crates", "", "| Crate | Version | License | Authors |", "| --- | --- | --- | --- |"]
    seen = set()
    for c in sorted(crates, key=lambda c: (c["name"].lower(), c.get("version", ""))):
        key = (c["name"], c.get("version"))
        if key in seen:
            continue
        seen.add(key)
        authors = (c.get("authors") or "").replace("|", ", ")
        notices.append(f"| {c['name']} | {c.get('version','')} | {c.get('license') or 'UNKNOWN'} | {authors[:80]} |")
    notices += ["", "## npm packages", "", "| Package | Version | License |", "| --- | --- | --- |"] + [f"| {n} | {v} | {l} |" for n, v, l, _ in npm]
    notices += ["", "## Binaries, models, fonts", ""]
    notices += [f"- `{f}` — {src} — {lic}" for f, src, sha, lic in mods]
    notices += [f"- `{f}` — {l}" for f, l in fnt]
    notices += ["- Hunspell en_GB-large word list — SCOWL (Kevin Atkinson), MIT-like permissive license", "- Webster's 1913 dictionary headwords — public domain (Project Gutenberg #29765)", ""]
    open("THIRD-PARTY-NOTICES.md", "w", encoding="utf-8", newline="\n").write("\n".join(notices))
    print(f"{len(crates)} crates, {len(npm)} npm packages, {len(mods)} binaries/models, {len(fnt)} fonts")


if __name__ == "__main__":
    main()
